name: background_location_tracker
description: A Flutter plugin that allows you to track the background location for Android & iOS
repository: https://github.com/icapps/flutter-background-location-tracker
version: 1.4.3

environment:
  sdk: ">=2.12.0"
  flutter: ">=2.0.0"

dependencies:
  background_fetch: ^1.3.3
  collection: ^1.15.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.background_location_tracker
        pluginClass: BackgroundLocationTrackerPlugin
      ios:
        pluginClass: TSBackgroundGeolocationPlugin
